### ISSUE TITLE
Some issues in the code

### ISSUE THREAD

**Issue by Kin-Zhang** [dcmlr/groundgrid#3]
https://github.com/dcmlr/groundgrid/blob/a143de798657122b04517c305222b08c888b940d/src/GroundGridNodelet.cpp#L107-L115

In the code above, I think the condition will always be true since:

`std::hypot(lastOdom->pose.pose.position.x-inOdom->pose.pose.position.x, 2.0f) + std::hypot(lastOdom->pose.pose.position.y-inOdom->pose.pose.position.y, 2.0f)` equal to $\sqrt{x^2+2^2}+\sqrt{y^2+2^2}$ and it will be always > 1, is that a mistake?

I think maybe you want to write `std::hypot(lastOdom->pose.pose.position.x-inOdom->pose.pose.position.x, lastOdom->pose.pose.position.y-inOdom->pose.pose.position.y)`. Then I think the condition should depend on the grid size we choose but not hard code here to 2 meters.

---

Reference: [hypot c++ func](https://en.cppreference.com/w/cpp/numeric/math/hypot)

**Comment by Nussknacker** [comment]
Hi @Kin-Zhang,
thank you for pointing this out. 
You are correct, this code is basically a no-op. Furthermore, it is never executed since the condition on the left is also always false. It was meant to throttle high-rate odometry topics but it is not needed in the case of the KITTI dataset. 
I will remove it with the next update.
